### ISSUE TITLE
There are some problems, I don't know if it's a bug

### ISSUE THREAD

**Issue by hongshi1** [YXHXianYu/Cookie-Escort-CER-65-RUS#5]
For instance ,in your mouse are in the panel and you click the right mouse and does not move, the character will repeatedly cross jump, I do not know whether it is a bug
 

Also because every computer screen is different, the size of a certain good program, for a few small screen resolution of the computer is not very friendly (although I don't know how to adjust myself, and directly put the resizable where set to true the whole drawing panel will such as scaling, I don't know), ahem problems under the simple feedback
 

Anyway,Page setup is very handsome!!

**Comment by YXHXianYu** [comment]
Pressing right button to dash continously is **not a bug**. The dash will be triggered **only once** if you click lightly. And you can dash a long distance if you hold the right button and aim a distant target.

Adaptive resolution is a problem. The adaptive resolution funcion **only works during fighting**, and it will **fail in the menu**. It's because I don't have enough time to add this funcion in the menu. TAT

Thank you for your appreciation and issues. :D
